Repository WildCodeSchool/orleans-0919-php-gabare, pull requests merged in 2019-12, with the labels that each got.

#24 initiate layout
  assets/js/app.js
  assets/scss/_vars.scss
  assets/scss/app.scss
  composer.json
  composer.lock
  package.json
  symfony.lock
  templates/base.html.twig
  templates/layout.html.twig
  templates/layoutAdmin.html.twig
  yarn.lock
Labels: reviewed

#25 add view animation
  assets/scss/animation_style.scss
  assets/scss/app.scss
  phpmd.xml
  src/Controller/GabareLifeController.php
  templates/gabare_life/includes/_animation.html.twig
  templates/gabare_life/index.html.twig
Labels: reviewed

#26 S01 us18
  .gitignore
  composer.json
  composer.lock
  config/bundles.php
  phpmd.xml
  src/Controller/GabareLifeController.php
  src/DataFixtures/ReportFixtures.php
  src/Entity/Report.php
  src/Repository/ReportRepository.php
  symfony.lock
  templates/gabare_life/includes/_report.html.twig
  templates/gabare_life/index.html.twig
Labels: reviewed by PO

#27 S01 actualities front
  assets/scss/_vars.scss
  assets/scss/animation_style.scss
  assets/scss/app.scss
  src/Controller/GabareLifeController.php
  src/DataFixtures/ArticleFixtures.php
  src/DataFixtures/ThemeFixtures.php
  src/Entity/Article.php
  src/Entity/Theme.php
  src/Repository/ArticleRepository.php
  src/Repository/ThemeRepository.php
  templates/gabare_life/includes/_actualities.html.twig
  templates/gabare_life/includes/_animation.html.twig
  templates/gabare_life/index.html.twig
  templates/layout.html.twig
  templates/layoutAdmin.html.twig
Labels: reviewed

#28 S01 us19
  assets/scss/app.scss
  assets/scss/presse_style.scss
  src/Controller/GabareLifeController.php
  src/DataFixtures/PresseFixtures.php
  src/Entity/Presse.php
  src/Repository/PresseRepository.php
  templates/gabare_life/includes/_presse.html.twig
  templates/gabare_life/index.html.twig
Labels: reviewed

#31 creation of the CRUD and work/style on index page only, other CRUD pa…
  assets/scss/admin_style.scss
  assets/scss/app.scss
  src/Controller/AdminReportController.php
  src/Form/ReportType.php
  templates/admin_report/_delete_form.html.twig
  templates/admin_report/_form.html.twig
  templates/admin_report/edit.html.twig
  templates/admin_report/index.html.twig
  templates/admin_report/new.html.twig
  templates/admin_report/show.html.twig
Labels: reviewed

#29 S01 us01
  assets/images/logo.png
  assets/scss/_vars.scss
  assets/scss/app.scss
  assets/scss/header_style.scss
  composer.lock
  src/Controller/HomeController.php
  symfony.lock
  templates/_header.html.twig
  templates/base.html.twig
  templates/home/index.html.twig
  templates/layout.html.twig
  webpack.config.js
Labels: reviewed

#33 delete function message changed
  templates/admin_report/_delete_form.html.twig
Labels: reviewed

#32 Sprint 1 : dev to master
  .gitignore
  assets/images/logo.png
  assets/js/app.js
  assets/scss/_vars.scss
  assets/scss/admin_style.scss
  assets/scss/animation_style.scss
  assets/scss/app.scss
  assets/scss/header_style.scss
  assets/scss/presse_style.scss
  composer.json
  composer.lock
  config/bundles.php
  package.json
  phpmd.xml
  src/Controller/AdminReportController.php
  src/Controller/GabareLifeController.php
  src/Controller/HomeController.php
  src/DataFixtures/ArticleFixtures.php
  src/DataFixtures/PresseFixtures.php
  src/DataFixtures/ReportFixtures.php
  src/DataFixtures/ThemeFixtures.php
  src/Entity/Article.php
  src/Entity/Presse.php
  src/Entity/Report.php
  src/Entity/Theme.php
  src/Form/ReportType.php
  src/Repository/ArticleRepository.php
  src/Repository/PresseRepository.php
  src/Repository/ReportRepository.php
  src/Repository/ThemeRepository.php
  symfony.lock
  templates/_header.html.twig
  templates/admin_report/_delete_form.html.twig
  templates/admin_report/_form.html.twig
  templates/admin_report/edit.html.twig
  templates/admin_report/index.html.twig
  templates/admin_report/new.html.twig
  templates/admin_report/show.html.twig
  templates/base.html.twig
  templates/gabare_life/includes/_actualities.html.twig
  templates/gabare_life/includes/_animation.html.twig
  templates/gabare_life/includes/_presse.html.twig
  templates/gabare_life/includes/_report.html.twig
  templates/gabare_life/index.html.twig
  templates/home/index.html.twig
  templates/layout.html.twig
  templates/layoutAdmin.html.twig
  webpack.config.js
  yarn.lock
Labels: reviewed

#67 Fix add animation fixtures
  .gitignore
  composer.json
  composer.lock
  package.json
  src/Controller/GabareLifeController.php
  src/DataFixtures/AnimationFixtures.php
  src/Entity/Animation.php
  src/Repository/AnimationRepository.php
  symfony.lock
  templates/gabare_life/includes/_animation.html.twig
  yarn.lock
Labels: reviewed

#69 S02 us38
  .eslintrc.yml
  assets/images/meeting.jpg
  config/packages/twig.yaml
  package.json
  src/Controller/AdminReportController.php
  src/Controller/GabareLifeController.php
  src/Entity/Report.php
  src/Form/ReportType.php
  templates/admin_report/_delete_form.html.twig
  templates/admin_report/_form.html.twig
  templates/admin_report/edit.html.twig
  templates/admin_report/index.html.twig
  templates/admin_report/new.html.twig
  webpack.config.js
  yarn.lock
Labels: reviewed

#74 US30 - read for CRUD animation
  src/Controller/AdminAnimationController.php
  src/Form/AnimationType.php
  templates/admin_animation/_delete_form.html.twig
  templates/admin_animation/_form.html.twig
  templates/admin_animation/edit.html.twig
  templates/admin_animation/index.html.twig
  templates/admin_animation/new.html.twig
  templates/admin_animation/show.html.twig
Labels: reviewed

#65 S01 us41
  assets/scss/admin_presse.scss
  assets/scss/admin_style.scss
  src/Controller/AdminPresseController.php
  src/Controller/GabareLifeController.php
  src/Form/PresseType.php
  templates/admin_presse/_delete_form.html.twig
  templates/admin_presse/_form.html.twig
  templates/admin_presse/edit.html.twig
  templates/admin_presse/new.html.twig
  templates/admin_presse/show.html.twig
Labels: reviewed

#70 S02 fix front css and responsive
  assets/images/report.jpg
  assets/scss/_vars.scss
  assets/scss/actualities_style.scss
  assets/scss/animation_style.scss
  assets/scss/app.scss
  assets/scss/presse_style.scss
  composer.json
  composer.lock
  config/packages/twig_extensions.yaml
  config/services.yaml
  src/DataFixtures/ArticleFixtures.php
  symfony.lock
  templates/gabare_life/includes/_actualities.html.twig
  templates/gabare_life/includes/_animation.html.twig
  templates/gabare_life/includes/_presse.html.twig
  templates/gabare_life/includes/_report.html.twig
  webpack.config.js
Labels: reviewed

#75 S09 US39 edit on CRUD (Report)
  templates/admin_report/edit.html.twig
Labels: reviewed

#76 S02 68 show details of report
  templates/admin_report/show.html.twig
Labels: reviewed

#83 fix alignement in connexion button and bootstrap js issues
  templates/_header.html.twig
Labels: reviewed

#73 S01 articles crud fix
  .gitignore
  composer.json
  composer.lock
  src/Controller/AdminArticleController.php
  src/Entity/Article.php
  src/Form/ArticleType.php
  templates/admin_article/_delete_form.html.twig
  templates/admin_article/_form.html.twig
  templates/admin_article/edit.html.twig
  templates/admin_article/index.html.twig
  templates/admin_article/new.html.twig
  templates/admin_article/show.html.twig
  templates/admin_report/show.html.twig
Labels: reviewed

#80 S01 us10
  assets/scss/app.scss
  assets/scss/footer_style.scss
  templates/_footer.html.twig
  templates/layout.html.twig
Labels: reviewed

#84 S02_US09 - transport information
  assets/images/bus.jpg
  templates/home/includes/_bus.html.twig
  templates/home/index.html.twig
Labels: reviewed

#81 S02 us29 - add animation (CRUD)
  src/Controller/AdminAnimationController.php
  src/Entity/Animation.php
  src/Form/AnimationType.php
  templates/admin_animation/_form.html.twig
  templates/admin_animation/new.html.twig
Labels: reviewed

#85 Priorité - fix branch dev
  src/Controller/GabareLifeController.php
Labels: reviewed

#82 S02_US32 - delete function message animation
  templates/admin_animation/_delete_form.html.twig
Labels: reviewed

#87 S02 us31 - edit animation
  src/Controller/AdminAnimationController.php
  templates/admin_animation/edit.html.twig
  templates/admin_report/edit.html.twig
Labels: reviewed

#90 S02US66 - show animation CRUD
  src/Controller/AdminAnimationController.php
  templates/admin_animation/show.html.twig
Labels: reviewed

#93 fix JS block problem
  templates/base.html.twig
  templates/gabare_life/index.html.twig
  templates/home/index.html.twig
  templates/layout.html.twig
Labels: reviewed

#86 S02 us43
  src/Controller/AdminPresseController.php
  src/Entity/Presse.php
  src/Form/PresseType.php
  templates/admin_presse/_delete_form.html.twig
  templates/admin_presse/_form.html.twig
  templates/admin_presse/edit.html.twig
  templates/admin_presse/new.html.twig
Labels: reviewed

#95 add fix navbar
  assets/scss/header_style.scss
  templates/_header.html.twig
Labels: reviewed

#92 S02 us06 form front
  composer.json
  composer.lock
  src/Controller/GabareLifeController.php
  src/Controller/HomeController.php
  src/Entity/Contact.php
  src/Form/ArticleType.php
  src/Form/ContactType.php
  templates/admin_article/index.html.twig
  templates/gabare_life/includes/_actualities.html.twig
  templates/home/includes/_form.html.twig
  templates/home/index.html.twig
Labels: reviewed

#94 paralax and image header removed in responsive
  templates/gabare_life/includes/_actualities.html.twig
  templates/gabare_life/includes/_animation.html.twig
Labels: reviewed

#98 S02 us08 - phone number on homepage
  assets/scss/app.scss
  assets/scss/phone_style.scss
  templates/home/includes/_phone.html.twig
  templates/home/index.html.twig
Labels: reviewed

#101 fix report edit
  templates/admin_report/edit.html.twig
Labels: reviewed

#100 S02 us7 map
  templates/gabare_life/includes/_animation.html.twig
  templates/home/includes/_form.html.twig
Labels: reviewed

#103 fix admin index pages
  assets/scss/admin_style.scss
  templates/admin_animation/index.html.twig
  templates/admin_article/_delete_form.html.twig
  templates/admin_article/index.html.twig
  templates/admin_report/index.html.twig
Labels: reviewed

#102 Fix - CSS and responsive correction
  assets/scss/actualities_style.scss
  assets/scss/animation_style.scss
  assets/scss/presse_style.scss
  templates/gabare_life/includes/_animation.html.twig
  templates/gabare_life/includes/_presse.html.twig
  templates/gabare_life/includes/_report.html.twig
Labels: reviewed

#104 home picture finish
  assets/images/welcome.jpg
  assets/scss/app.scss
  assets/scss/header_style.scss
  assets/scss/welcome.scss
  templates/_header.html.twig
  templates/home/includes/_welcome.html.twig
  templates/home/index.html.twig
Labels: Priority !, reviewed

#106 FIX style admin article
  templates/admin_article/edit.html.twig
  templates/admin_article/show.html.twig
Labels: reviewed

#107 fix button direction
  templates/admin_presse/edit.html.twig
Labels: Priority !, reviewed

#105 Delete cooperator line it corresponds to another user story
  assets/scss/header_style.scss
  templates/_header.html.twig
Labels: reviewed

#168 Fix phone information front css
  assets/scss/phone_style.scss
  templates/home/includes/_phone.html.twig
Labels: reviewed

#192 S03 us6 wysiwyg
  composer.json
  composer.lock
  config/bundles.php
  config/packages/fos_ckeditor.yaml
  package.json
  src/Form/ArticleType.php
  symfony.lock
  templates/admin_article/show.html.twig
  templates/gabare_life/includes/_actualities.html.twig
  webpack.config.js
  yarn.lock
Labels: reviewed

#193 fix update part was mixed up with add
  templates/admin_report/edit.html.twig
Labels: reviewed

#194 Fix size problem for images in card
  assets/scss/actualities_style.scss
  assets/scss/animation_style.scss
  templates/gabare_life/includes/_actualities.html.twig
  templates/gabare_life/includes/_animation.html.twig
Labels: reviewed

#197 fix home picture done
  assets/images/grocery-store-2119702_1920.jpg
  assets/scss/animation_style.scss
  assets/scss/app.scss
  assets/scss/welcome.scss
  templates/home/includes/_welcome.html.twig
Labels: Priority !, reviewed

#199 fix as to copy Lucas and refactor code
  assets/etalage3.jpg
  assets/images/etalage.jpg
  assets/images/etalage.png
  assets/images/etalage2.jpg
  assets/images/etalage3.jpg
  templates/gabare_life/includes/_animation.html.twig
  templates/gabare_life/includes/_stripe.html.twig
  templates/gabare_life/index.html.twig
Labels: Priority !, reviewed

#195 FIX form
  assets/scss/app.scss
  assets/scss/form.scss
  templates/home/includes/_form.html.twig
Labels: reviewed

#198 add active links"
  assets/js/app.js
  assets/scss/header_style.scss
  templates/_header.html.twig
  templates/gabare_life/index.html.twig
  templates/home/index.html.twig
Labels: reviewed

#196 S02 us5
  assets/images/interieur.jpg
  assets/images/rayon.jpg
  assets/scss/app.scss
  assets/scss/gabare_brief_style.scss
  templates/home/includes/_gabare.html.twig
  templates/home/index.html.twig
Labels: reviewed

#207 fix home page image
  assets/scss/app.scss
  templates/_header.html.twig
  templates/home/includes/_welcome.html.twig
Labels: reviewed

#202 S03_US12 bandeau image page Qui sommes-nous
  assets/images/jam.jpg
  assets/scss/app.scss
  src/Controller/AboutUsController.php
  templates/about_us/includes/_stripe.html.twig
  templates/about_us/index.html.twig
Labels: reviewed

#201 S03US15 - create entities Worker and Activity
  src/Entity/Activity.php
  src/Entity/Worker.php
  src/Repository/ActivityRepository.php
  src/Repository/WorkerRepository.php
Labels: reviewed

#210 fix to display page Qui sommes nous
  templates/_header.html.twig
  templates/about_us/index.html.twig
Labels: Priority !, reviewed

#208 US03_20_bis image accueil page Nous rejoindre
  assets/images/bread.jpg
  src/Controller/JoinUsController.php
  templates/_header.html.twig
  templates/join_us/includes/_stripe.html.twig
  templates/join_us/index.html.twig
Labels: reviewed

#209 add fixtures for Worker and Activity
  src/DataFixtures/ActivityFixtures.php
  src/DataFixtures/WorkerFixtures.php
Labels: reviewed

#213 S03 fix color button home
  assets/scss/form.scss
  assets/scss/gabare_brief_style.scss
  templates/home/includes/_form.html.twig
  templates/home/includes/_gabare.html.twig
Labels: reviewed

#214 Fix bus infos - ajout couleur lignes TAO
  assets/scss/_vars.scss
  assets/scss/app.scss
  assets/scss/bus_style.scss
  templates/home/includes/_bus.html.twig
Labels: reviewed

#211 S03US65 - page QSN afficher les pionniers
  src/Controller/AboutUsController.php
  src/DataFixtures/WorkerFixtures.php
  src/Repository/WorkerRepository.php
  templates/about_us/includes/_pioneer.html.twig
  templates/about_us/index.html.twig
Labels: reviewed

#216 S03_US20 front subscription details
  assets/etalage3.jpg
  assets/images/door-join-us-2.jpg
  assets/images/student.jpg
  templates/join_us/includes/_inscription.html.twig
  templates/join_us/includes/_stripe.html.twig
  templates/join_us/index.html.twig
Labels: reviewed

#217 S03US15C - afficher salariés
  assets/images/Portrait_Placeholder.jpg
  assets/scss/app.scss
  assets/scss/employee_style.scss
  src/Controller/AboutUsController.php
  src/Repository/WorkerRepository.php
  templates/about_us/includes/_employee.html.twig
  templates/about_us/index.html.twig
Labels: reviewed
