Repository WildCodeSchool/orleans-0919-php-gabare, pull requests merged in 2020-01, with the labels that each got.

#218 S03_US22 front 2 forms
  assets/scss/app.scss
  assets/scss/joinforms_style.scss
  templates/join_us/includes/_forms.html.twig
  templates/join_us/index.html.twig
Labels: reviewed

#219 S03 us21 agenda
  assets/scss/app.scss
  assets/scss/timetable.scss
  composer.lock
  config/services.yaml
  src/Controller/JoinUsController.php
  src/DataFixtures/TimetableFixtures.php
  src/Entity/Timetable.php
  src/Repository/TimetableRepository.php
  templates/join_us/includes/_timetable.html.twig
  templates/join_us/index.html.twig
Labels: reviewed

#221 add some class and change button/picture of the Brief part
  assets/scss/gabare_brief_style.scss
  templates/home/includes/_gabare.html.twig
Labels: reviewed

#222 S03US15X - ajout membres CA
  assets/scss/app.scss
  assets/scss/profile_card.scss
  src/Controller/AboutUsController.php
  src/Repository/WorkerRepository.php
  templates/about_us/includes/_CA-Member.html.twig
  templates/about_us/index.html.twig
Labels: reviewed

#223 links added
  assets/scss/app.scss
  src/Controller/GabareLifeController.php
  templates/_footer.html.twig
  templates/_header.html.twig
  templates/about_us/includes/_employee.html.twig
  templates/about_us/includes/_pioneer.html.twig
  templates/gabare_life/includes/_actualities.html.twig
  templates/gabare_life/includes/_animation.html.twig
  templates/gabare_life/includes/_presse.html.twig
  templates/gabare_life/includes/_report.html.twig
  templates/gabare_life/index.html.twig
  templates/home/includes/_form.html.twig
  templates/home/includes/_phone.html.twig
  templates/join_us/includes/_forms.html.twig
  templates/join_us/includes/_inscription.html.twig
Labels: Priority !, reviewed

#224 fix bug affichage entité Timetable
  src/Entity/Timetable.php
Labels: Priority !, reviewed

#212 S03_US56 side menu admin
  assets/scss/_vars.scss
  assets/scss/admin_menu.scss
  assets/scss/admin_style.scss
  templates/_admin_nav.html.twig
  templates/admin_animation/edit.html.twig
  templates/admin_animation/index.html.twig
  templates/admin_animation/new.html.twig
  templates/admin_animation/show.html.twig
  templates/admin_article/edit.html.twig
  templates/admin_article/index.html.twig
  templates/admin_article/new.html.twig
  templates/admin_article/show.html.twig
  templates/admin_presse/edit.html.twig
  templates/admin_presse/show.html.twig
  templates/admin_report/edit.html.twig
  templates/admin_report/index.html.twig
  templates/admin_report/new.html.twig
  templates/admin_report/show.html.twig
  templates/base.html.twig
  templates/layout.html.twig
  templates/layoutAdmin.html.twig
Labels: Priority !, reviewed

#227 S03US15E - ajout CA les amis de la gabare
  src/Controller/AboutUsController.php
  src/Repository/WorkerRepository.php
  templates/about_us/includes/_CA-Friend.html.twig
  templates/about_us/index.html.twig
Labels: reviewed

#229 fix links
  assets/images/supermarket.jpg
  assets/scss/joinforms_style.scss
  templates/_header.html.twig
  templates/join_us/includes/_forms.html.twig
  templates/join_us/includes/_inscription.html.twig
Labels: Priority !, reviewed

#225 S03 us12 histoire
  assets/scss/app.scss
  assets/scss/history.scss
  package.json
  templates/about_us/includes/_history.html.twig
  templates/about_us/index.html.twig
  templates/admin_article/_delete_form.html.twig
  templates/admin_article/index.html.twig
  yarn.lock
Labels: reviewed

#241 S04 us45_ CRUD index agenda
  composer.json
  composer.lock
  config/services.yaml
  src/Controller/AdminTimetableController.php
  src/Form/TimetableType.php
  symfony.lock
  templates/_admin_nav.html.twig
  templates/admin_timetable/_delete_form.html.twig
  templates/admin_timetable/_form.html.twig
  templates/admin_timetable/edit.html.twig
  templates/admin_timetable/index.html.twig
  templates/admin_timetable/new.html.twig
  templates/admin_timetable/show.html.twig
Labels: Priority !, reviewed

#230 all reports files deleted
  assets/scss/app.scss
  assets/scss/report_style.scss
  src/Controller/AdminReportController.php
  src/Controller/GabareLifeController.php
  src/DataFixtures/ReportFixtures.php
  src/Entity/Report.php
  src/Form/ReportType.php
  src/Repository/ReportRepository.php
  templates/_admin_nav.html.twig
  templates/admin_report/_delete_form.html.twig
  templates/admin_report/_form.html.twig
  templates/admin_report/edit.html.twig
  templates/admin_report/index.html.twig
  templates/admin_report/new.html.twig
  templates/admin_report/show.html.twig
Labels: reviewed

#233 carousel entity/faker
  src/DataFixtures/CarouselFixtures.php
  src/Entity/Carousel.php
  src/Repository/CarouselRepository.php
Labels: reviewed

#243 S03 us06 send mail
  .gitignore
  assets/scss/app.scss
  composer.json
  composer.lock
  config/services.yaml
  src/Controller/HomeController.php
  src/Entity/Contact.php
  symfony.lock
  templates/_flash_message.html.twig
  templates/base.html.twig
  templates/emails/_contact.html.twig
  templates/home/index.html.twig
Labels: reviewed

#247 fix base layout
  templates/base.html.twig
Labels: Priority !, reviewed

#236 localizedate
  config/services.yaml
  templates/join_us/includes/_timetable.html.twig
Labels: reviewed

#248 S04 us81 alerte on homage (front/fixture)
  assets/scss/alert_style.scss
  assets/scss/app.scss
  src/Controller/HomeController.php
  src/DataFixtures/AlertFixtures.php
  src/Entity/Alert.php
  src/Repository/AlertRepository.php
  templates/home/includes/_welcome.html.twig
Labels: reviewed

#228 S03US49 - ajout CRUD Index Worker
  src/Controller/AdminWorkerController.php
  src/Entity/Carousel.php
  src/Form/WorkerType.php
  src/Repository/WorkerRepository.php
  templates/admin_worker/_delete_form.html.twig
  templates/admin_worker/_form.html.twig
  templates/admin_worker/edit.html.twig
  templates/admin_worker/index.html.twig
  templates/admin_worker/new.html.twig
  templates/admin_worker/show.html.twig
Labels: Priority !, reviewed

#244 Fix rendez-vous client
  assets/scss/admin_style.scss
  src/Controller/AdminAnimationController.php
  src/Controller/AdminArticleController.php
  templates/_admin_nav.html.twig
  templates/about_us/includes/_CA-Friend.html.twig
  templates/about_us/includes/_CA-Member.html.twig
  templates/about_us/includes/_employee.html.twig
  templates/about_us/includes/_pioneer.html.twig
  templates/admin_animation/_delete_form.html.twig
  templates/admin_animation/edit.html.twig
  templates/admin_animation/index.html.twig
  templates/admin_animation/new.html.twig
  templates/admin_animation/show.html.twig
  templates/admin_article/_delete_form.html.twig
  templates/admin_article/edit.html.twig
  templates/admin_article/index.html.twig
  templates/admin_article/new.html.twig
  templates/admin_article/show.html.twig
  templates/join_us/includes/_forms.html.twig
  templates/join_us/includes/_timetable.html.twig
Labels: Priority !, reviewed

#253 S04 US46 - Add (Crud agenda)
  src/Controller/AdminTimetableController.php
  src/Form/TimetableType.php
  templates/admin_timetable/_form.html.twig
  templates/admin_timetable/new.html.twig
  templates/admin_timetable/show.html.twig
Labels: reviewed

#257 S04 US47 update Timetable
  src/Controller/AdminTimetableController.php
  templates/admin_timetable/edit.html.twig
  templates/admin_timetable/index.html.twig
Labels: reviewed

#259 S04_US58 delete function Agenda
  templates/admin_timetable/_delete_form.html.twig
  templates/admin_timetable/index.html.twig
Labels: reviewed

#260 S04US50 - Add Worker CRUD
  src/Form/WorkerType.php
  templates/_admin_nav.html.twig
  templates/admin_worker/index.html.twig
  templates/admin_worker/new.html.twig
Labels: Priority !, reviewed

#258 finish front carousel
  .gitignore
  assets/js/app.js
  assets/scss/app.scss
  assets/scss/carousel.scss
  src/Controller/HomeController.php
  templates/home/includes/_carousel.html.twig
  templates/home/index.html.twig
Labels: reviewed

#265 S04 us84
  assets/scss/admin_style.scss
  src/Controller/ThemeController.php
  src/DataFixtures/ThemeFixtures.php
  src/Entity/Theme.php
  src/Form/ThemeType.php
  templates/_admin_nav.html.twig
  templates/admin_theme/_delete_form.html.twig
  templates/admin_theme/_form.html.twig
  templates/admin_theme/edit.html.twig
  templates/admin_theme/index.html.twig
  templates/admin_theme/new.html.twig
  templates/admin_theme/show.html.twig
Labels: reviewed

#254 S04 us91A - connexion API
  .env
  composer.json
  composer.lock
  config/services.yaml
  src/Controller/ProductController.php
  src/Entity/Product.php
  src/Repository/ProductRepository.php
  src/Service/ConnectOdooService.php
  symfony.lock
  templates/products/includes/_products.html.twig
  templates/products/index.html.twig
Labels: Priority !, reviewed

#267 ajout des liens carousel
  assets/scss/carousel.scss
  src/DataFixtures/CarouselFixtures.php
  templates/home/includes/_carousel.html.twig
Labels: reviewed

#268 finich add theme
  src/Controller/AdminThemeController.php
  src/Form/ThemeType.php
  templates/admin_theme/index.html.twig
  templates/admin_theme/new.html.twig
Labels: reviewed

#242 S04US14 - ajout partenaires
  assets/images/partenaires/partenaire-1.jpg
  assets/images/partenaires/partenaire-10.jpg
  assets/images/partenaires/partenaire-11.jpg
  assets/images/partenaires/partenaire-12.jpg
  assets/images/partenaires/partenaire-2.jpg
  assets/images/partenaires/partenaire-3.jpg
  assets/images/partenaires/partenaire-4.jpg
  assets/images/partenaires/partenaire-5.jpg
  assets/images/partenaires/partenaire-6.jpg
  assets/images/partenaires/partenaire-7.jpg
  assets/images/partenaires/partenaire-8.jpg
  assets/images/partenaires/partenaire-9.jpg
  assets/scss/_vars.scss
  assets/scss/app.scss
  assets/scss/partners_style.scss
  src/Controller/AboutUsController.php
  templates/about_us/includes/_partners.html.twig
  templates/about_us/index.html.twig
Labels: reviewed

#261 creation of different user
  assets/scss/app.scss
  assets/scss/login_style.scss
  config/packages/security.yaml
  config/routes.yaml
  src/Controller/SecurityController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/User.php
  src/Repository/UserRepository.php
  src/Security/LoginFormAuthenticator.php
  templates/_admin_nav.html.twig
  templates/_header.html.twig
  templates/security/login.html.twig
Labels: reviewed

#271 S04US51 - CRUD update Worker
  src/Controller/AdminWorkerController.php
  src/Form/WorkerType.php
  templates/admin_worker/edit.html.twig
Labels: reviewed

#264 S04 us58 show articles
  assets/scss/app.scss
  assets/scss/article.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/stof_doctrine_extensions.yaml
  src/Controller/ArticleController.php
  src/Controller/GabareLifeController.php
  src/DataFixtures/ArticleFixtures.php
  src/Entity/Article.php
  symfony.lock
  templates/article/list.html.twig
  templates/article/show.html.twig
  templates/gabare_life/includes/_actualities.html.twig
  templates/gabare_life/includes/_articles.html.twig
  templates/gabare_life/index.html.twig
Labels: reviewed

#273 add a parenthese for the entity USER
  src/Entity/User.php
Labels: Priority !, reviewed

#269 Values with fixture and API
  assets/js/app.js
  assets/scss/app.scss
  assets/scss/values.style.scss
  src/Controller/AboutUsController.php
  src/DataFixtures/ValueFixtures.php
  src/Entity/Value.php
  src/Repository/CustomerRepository.php
  src/Repository/ProductRepository.php
  src/Repository/ValueRepository.php
  templates/about_us/includes/_values.html.twig
  templates/about_us/index.html.twig
Labels: reviewed

#272 API search bar
  assets/scss/app.scss
  assets/scss/product_style.scss
  src/Controller/ProductController.php
  src/Entity/Product.php
  src/Form/SearchProductType.php
  src/Repository/ProductRepository.php
  templates/products/includes/_products.html.twig
Labels: Priority !, reviewed

#277 fix probleme de redirection login
  src/Security/LoginFormAuthenticator.php
Labels: Priority !, reviewed

#278 COrrection redirection admin article
  templates/admin_article/index.html.twig
Labels: reviewed

#282 fix date
  config/packages/twig_extensions.yaml
  config/services.yaml
  src/DataFixtures/TimetableFixtures.php
  src/Repository/TimetableRepository.php
  templates/join_us/includes/_timetable.html.twig
Labels: Priority !, reviewed

#280 update part theme done
  src/Controller/AdminThemeController 2.php
  templates/admin_theme/_delete_form.html.twig
  templates/admin_theme/edit.html.twig
Labels: reviewed

#279 S04 fix title histoire
  src/Controller/ArticleController.php
  templates/about_us/includes/_history.html.twig
  templates/admin_history/edit.html.twig
  templates/admin_history/show.html.twig
Labels: reviewed

#283 S04 us79 - show crud Worker
  assets/scss/admin_style.scss
  templates/admin_worker/show.html.twig
Labels: reviewed

#297 S05US100 - page 404
  assets/images/compass.jpeg
  assets/scss/app.scss
  assets/scss/error_style.scss
  templates/bundles/TwigBundle/Exception/error404.html.twig
  templates/layout_error.html.twig
Labels: reviewed

#298 S05 us99 home page admin with ReadMe
  assets/scss/admin_manual.scss
  assets/scss/admin_menu.scss
  assets/scss/admin_style.scss
  src/Controller/AdminHomeController.php
  src/Security/LoginFormAuthenticator.php
  templates/_admin_nav.html.twig
  templates/admin_home/index.html.twig
Labels: reviewed

#299 S04 us59 article pagination
  composer.json
  composer.lock
  config/bundles.php
  config/packages/knp_paginator.yml
  config/packages/twig.yaml
  src/Controller/ArticleController.php
  src/DataFixtures/ArticleFixtures.php
  src/Repository/ArticleRepository.php
  symfony.lock
  templates/article/list.html.twig
  translations/KnpPaginatorBundle.fr.yml
Labels: reviewed

#306 S05_US76A-
  src/Controller/ValueController.php
  src/Form/ValueType.php
  templates/value/_delete_form.html.twig
  templates/value/_form.html.twig
  templates/value/edit.html.twig
  templates/value/index.html.twig
  templates/value/new.html.twig
  templates/value/show.html.twig
Labels: Priority !, reviewed

#296 S05_US2_COOP
  assets/scss/header_style.scss
  config/packages/framework.yaml
  src/Controller/ArticleController.php
  src/Controller/GabareLifeController.php
  src/Controller/HeaderController.php
  src/Controller/HomeController.php
  src/Controller/JoinUsController.php
  src/Controller/ProductController.php
  src/Controller/SecurityController.php
  templates/_customers.html.twig
  templates/_header.html.twig
Labels: reviewed

#303 S05_US100 filter admin instructions by login access
  src/Controller/AdminHomeController.php
  templates/admin_home/index.html.twig
Labels: reviewed

#309 S05_US76B_Update
  src/Form/ValueType.php
  templates/value/edit.html.twig
Labels: reviewed

#310 S05US52 - delete Worker CRUD
  src/Controller/AdminWorkerController.php
  templates/admin_worker/_delete_form.html.twig
  templates/admin_worker/index.html.twig
Labels: reviewed

#313 S05_76D delete button
  templates/value/_delete_form.html.twig
Labels: reviewed

#311 S05_76C Function ADD for the value
  templates/value/new.html.twig
Labels: reviewed

#315 SO5_76E flash message and road name
  config/packages/webpack_encore.yaml
  src/Controller/AdminValueController.php
  templates/admin_value/_delete_form.html.twig
  templates/admin_value/_form.html.twig
  templates/admin_value/edit.html.twig
  templates/admin_value/index.html.twig
  templates/admin_value/new.html.twig
  templates/admin_value/show.html.twig
Labels: reviewed

#307 S05 us98 upload
  .gitignore
  assets/images/placeholder1.png
  composer.json
  composer.lock
  config/bundles.php
  config/packages/twig.yaml
  config/packages/vich_uploader.yaml
  src/Controller/ArticleController.php
  src/DataFixtures/ArticleFixtures.php
  src/Entity/Article.php
  src/Form/ArticleType.php
  src/Security/LoginFormAuthenticator.php
  symfony.lock
  templates/admin_article/edit.html.twig
  templates/admin_article/index.html.twig
  templates/admin_article/show.html.twig
  templates/article/list.html.twig
  templates/article/show.html.twig
  templates/gabare_life/includes/_articles.html.twig
Labels: reviewed

#319 S05_US97b admin user
  src/Controller/RegistrationController.php
  src/Entity/User.php
  src/Form/RegistrationFormType.php
  templates/registration/register.html.twig
Labels: reviewed

#321 S05US74A - CRUD carrousel index
  src/Controller/AdminCarouselController.php
  src/Form/CarouselType.php
  templates/_admin_nav.html.twig
  templates/admin_carousel/_delete_form.html.twig
  templates/admin_carousel/_form.html.twig
  templates/admin_carousel/edit.html.twig
  templates/admin_carousel/index.html.twig
  templates/admin_carousel/new.html.twig
  templates/admin_carousel/show.html.twig
Labels: reviewed

#326 S05 us37 CRUD Presse index
  src/Controller/AdminPresseController.php
  src/Form/Presse1Type.php
  templates/admin_presse/_delete_form.html.twig
  templates/admin_presse/_form.html.twig
  templates/admin_presse/edit.html.twig
  templates/admin_presse/index.html.twig
  templates/admin_presse/new.html.twig
  templates/admin_presse/show.html.twig
Labels: reviewed

#320 S05 us91 b
  assets/scss/product_style.scss
  src/Controller/ProductController.php
  src/Entity/Category.php
  src/Repository/CategoryRepository.php
  src/Repository/ProductRepository.php
  templates/admin_theme/index.html.twig
  templates/products/includes/_product_cards.html.twig
  templates/products/includes/_products.html.twig
  templates/products/show_products.html.twig
Labels: Priority !, reviewed

#344 fix upload sur animation
  config/packages/vich_uploader.yaml
  src/Controller/AdminPresseController.php
  src/DataFixtures/AnimationFixtures.php
  src/Entity/Animation.php
  src/Entity/Article.php
  src/Form/AnimationType.php
  templates/admin_animation/edit.html.twig
  templates/admin_animation/new.html.twig
  templates/admin_animation/show.html.twig
  templates/gabare_life/includes/_animation.html.twig
Labels: reviewed

#331 S05_US42 edit (valider après le presse add)
  templates/admin_presse/edit.html.twig
Labels: reviewed

#330 S05_97A_ROLE
  config/packages/security.yaml
  src/Controller/AdminAlertController.php
  src/Controller/AdminAnimationController.php
  src/Controller/AdminArticleController.php
  src/Controller/AdminCapitalController.php
  src/Controller/AdminCarouselController.php
  src/Controller/AdminHistoryController.php
  src/Controller/AdminPresseController.php
  src/Controller/AdminThemeController.php
  src/Controller/AdminTimetableController.php
  src/Controller/AdminWorkerController.php
  src/Controller/RegistrationController.php
  src/DataFixtures/UserFixtures.php
  src/Form/RegistrationFormType.php
  templates/registration/register.html.twig
Labels: reviewed

#348 S05US74D - CRUD carrousel SHOW
  templates/admin_carousel/show.html.twig
Labels: reviewed

#351 S05_US43 CRUD Presse delete
  src/Controller/AdminPresseController.php
  src/Controller/AdminThemeController 2.php
  templates/admin_presse/_delete_form.html.twig
Labels: reviewed

#349 S05US74C - CRUD carrousel EDIT
  src/Controller/AdminCarouselController.php
  templates/admin_carousel/edit.html.twig
Labels: reviewed

#350 Update presse front
  assets/scss/presse_style.scss
  src/Controller/GabareLifeController.php
  templates/gabare_life/includes/_presse.html.twig
Labels: reviewed

#352 S05 us60 filtered article
  src/Controller/ArticleController.php
  src/Form/ArticleType.php
  src/Form/ArticleTypeSearchType.php
  src/Repository/ArticleRepository.php
  templates/_customers.html.twig
  templates/article/list.html.twig
Labels: reviewed

#353 fix delete on CRUD Carousel
  templates/admin_carousel/_delete_form.html.twig
  templates/admin_carousel/index.html.twig
Labels: reviewed

#355 S05_US43_Presse show
  templates/admin_presse/show.html.twig
Labels: reviewed

#356 Fix upload worker
  assets/scss/admin_style.scss
  src/Controller/AdminWorkerController.php
  src/DataFixtures/WorkerFixtures.php
  src/Entity/Worker.php
  src/Form/WorkerType.php
  templates/admin_worker/edit.html.twig
  templates/admin_worker/new.html.twig
  templates/admin_worker/show.html.twig
Labels: reviewed

#358 FIX send mail
  templates/emails/_contact.html.twig
  templates/layoutEmail.html.twig
Labels: reviewed

#360 fix color theme front
  templates/gabare_life/includes/_articles.html.twig
Labels: reviewed

#364 front style on homepage : phone section
  assets/images/sea-min.jpg
  assets/scss/phone_style.scss
  templates/home/includes/_phone.html.twig
Labels: reviewed

#365 S05 98 upload history
  src/DataFixtures/HistoryFixtures.php
  src/Entity/History.php
  src/Form/HistoryType.php
  templates/about_us/includes/_history.html.twig
  templates/admin_history/edit.html.twig
  templates/admin_history/show.html.twig
Labels: reviewed

#367 Fix login page
  assets/scss/login_style.scss
  templates/security/login.html.twig
Labels: reviewed

#368 style and responsive done
  assets/images/rayon.jpg
  assets/scss/gabare_brief_style.scss
  templates/home/includes/_carousel.html.twig
  templates/home/includes/_gabare.html.twig
Labels: reviewed

#369 Add text for user manual - history and add button on intro
  templates/admin_home/includes/_foraboutus.html.twig
  templates/admin_home/includes/_intro.html.twig
Labels: reviewed

#370 S05_ EDIT / SHOW / DELETE User
  src/Controller/RegistrationController.php
  src/Form/RegistrationFormType.php
  templates/registration/delete.html.twig
  templates/registration/edit.html.twig
  templates/registration/index.html.twig
Labels: reviewed

#372 Dev to Master - 17 Janvier
  assets/images/rayon.jpg
  assets/images/sea-min.jpg
  assets/scss/admin_style.scss
  assets/scss/gabare_brief_style.scss
  assets/scss/login_style.scss
  assets/scss/phone_style.scss
  src/Controller/AdminCarouselController.php
  src/Controller/AdminWorkerController.php
  src/Controller/RegistrationController.php
  src/DataFixtures/CarouselFixtures.php
  src/DataFixtures/HistoryFixtures.php
  src/DataFixtures/WorkerFixtures.php
  src/Entity/Carousel.php
  src/Entity/History.php
  src/Entity/Worker.php
  src/Form/CarouselType.php
  src/Form/HistoryType.php
  src/Form/RegistrationFormType.php
  src/Form/WorkerType.php
  templates/_admin_nav.html.twig
  templates/_header.html.twig
  templates/about_us/includes/_CA-Friend.html.twig
  templates/about_us/includes/_CA-Member.html.twig
  templates/about_us/includes/_capital.html.twig
  templates/about_us/includes/_employee.html.twig
  templates/about_us/includes/_history.html.twig
  templates/about_us/includes/_partners.html.twig
  templates/admin_carousel/edit.html.twig
  templates/admin_carousel/index.html.twig
  templates/admin_carousel/new.html.twig
  templates/admin_carousel/show.html.twig
  templates/admin_history/edit.html.twig
  templates/admin_history/show.html.twig
  templates/admin_home/includes/_foraboutus.html.twig
  templates/admin_home/includes/_intro.html.twig
  templates/admin_worker/edit.html.twig
  templates/admin_worker/new.html.twig
  templates/admin_worker/show.html.twig
  templates/emails/_contact.html.twig
  templates/gabare_life/includes/_animation.html.twig
  templates/gabare_life/includes/_articles.html.twig
  templates/home/includes/_carousel.html.twig
  templates/home/includes/_gabare.html.twig
  templates/home/includes/_phone.html.twig
  templates/join_us/includes/_inscription.html.twig
  templates/join_us/includes/_timetable.html.twig
  templates/layoutEmail.html.twig
  templates/registration/delete.html.twig
  templates/registration/edit.html.twig
  templates/registration/index.html.twig
  templates/security/login.html.twig
Labels: reviewed

#376 Stylefix cooperator alert
  assets/scss/alert_style.scss
  assets/scss/app.scss
  assets/scss/header_style.scss
  src/Controller/HeaderController.php
  src/Controller/HomeController.php
  templates/_cooperators_and_alert.html.twig
  templates/_customers.html.twig
  templates/home/includes/_carousel.html.twig
  templates/home/includes/_welcome.html.twig
Labels: reviewed

#375 Fix show user
  src/Controller/RegistrationController.php
  templates/_admin_nav.html.twig
  templates/registration/index.html.twig
  templates/registration/register.html.twig
Labels: reviewed

#374 Add text and corrections
  templates/admin_home/includes/_foraboutus.html.twig
  templates/admin_home/includes/_forgabarelife.html.twig
Labels: reviewed

#373 S05 us103 fix
  assets/scss/product_style.scss
  src/Controller/ProductController.php
  src/Entity/Category.php
  src/Entity/Product.php
  src/Form/SearchProductType.php
  src/Repository/CategoryRepository.php
  src/Repository/ProductRepository.php
  templates/products/includes/_product_cards.html.twig
  templates/products/includes/_products.html.twig
  templates/products/show_products.html.twig
Labels: reviewed

#377 Fix card profile - responsive cards
  assets/js/scroll.js
  assets/scss/profile_card.scss
  src/Repository/WorkerRepository.php
  templates/about_us/includes/_CA-Friend.html.twig
  templates/about_us/includes/_CA-Member.html.twig
  templates/about_us/includes/_employee.html.twig
  templates/about_us/index.html.twig
  templates/article/list.html.twig
  templates/base.html.twig
  webpack.config.js
Labels: reviewed

#379 fix values css and responsive
  assets/scss/app.scss
  assets/scss/values.style.scss
  src/DataFixtures/CapitalFixtures.php
  templates/about_us/includes/_capital.html.twig
Labels: reviewed

#380 Stylefix page joinus
  assets/images/nous-rejoindre-2-min.jpg
  assets/scss/joinforms_style.scss
  assets/scss/timetable.scss
  src/DataFixtures/TimetableFixtures.php
  src/Entity/Timetable.php
  src/Form/TimetableType.php
  templates/admin_timetable/edit.html.twig
  templates/admin_timetable/index.html.twig
  templates/admin_timetable/new.html.twig
  templates/join_us/includes/_forms.html.twig
  templates/join_us/includes/_inscription.html.twig
  templates/join_us/includes/_stripe.html.twig
  templates/join_us/includes/_timetable.html.twig
Labels: reviewed

#381 Fix history front and responsive
  assets/scss/app.scss
  assets/scss/history.scss
  src/DataFixtures/HistoryFixtures.php
  templates/about_us/includes/_history.html.twig
Labels: reviewed

#382 Fix partners front and responsive
  templates/about_us/includes/_partners.html.twig
Labels: reviewed

#383 S05 us103 b
  assets/scss/product_style.scss
  src/Controller/ProductController.php
  templates/products/includes/_products.html.twig
Labels: reviewed

#378 Add text Carrousel manual
  templates/admin_home/includes/_forhomepage.html.twig
Labels: reviewed

#384 Stylefix home iframe
  assets/images/permanence.jpg
  assets/scss/form.scss
  assets/scss/phone_style.scss
Labels: reviewed

#385 shadows on all cards
  assets/scss/app.scss
  templates/article/list.html.twig
  templates/gabare_life/includes/_animation.html.twig
  templates/gabare_life/includes/_articles.html.twig
  templates/join_us/includes/_forms.html.twig
  templates/join_us/includes/_timetable.html.twig
Labels: reviewed

#386 fix admin style and add a page for the navAdmin
  assets/scss/admin_style.scss
  src/Controller/AdminHistoryController.php
  templates/_admin_nav.html.twig
  templates/admin_animation/show.html.twig
  templates/admin_article/show.html.twig
  templates/admin_capital/show.html.twig
  templates/admin_carousel/show.html.twig
  templates/admin_history/edit.html.twig
  templates/admin_history/index.html.twig
  templates/admin_history/show.html.twig
  templates/admin_presse/edit.html.twig
  templates/admin_presse/show.html.twig
  templates/admin_theme/index.html.twig
  templates/admin_timetable/index.html.twig
  templates/admin_timetable/new.html.twig
  templates/admin_worker/show.html.twig
Labels: reviewed

#388 fix front page about us
  assets/images/Portrait_Placeholder.jpg
  assets/images/Portrait_Placeholder.png
  assets/images/bread.jpg
  assets/scss/CAMember_style.scss
  assets/scss/app.scss
  assets/scss/pioneer_style.scss
  templates/about_us/includes/_CA-Friend.html.twig
  templates/about_us/includes/_CA-Member.html.twig
  templates/about_us/includes/_employee.html.twig
  templates/about_us/includes/_pioneer.html.twig
Labels: reviewed

#389 fix vich upload
  templates/about_us/includes/_CA-Friend.html.twig
Labels: reviewed

#391 fix alert message
  assets/scss/header_style.scss
  templates/_cooperators_and_alert.html.twig
Labels: reviewed

#390 add products to the navabar
  .gitignore
  assets/images/favicon.ico
  assets/scss/header_style.scss
  templates/_header.html.twig
  templates/base.html.twig
  templates/layout.html.twig
Labels: reviewed

#393 change css admin page
  assets/scss/admin_style.scss
  src/Controller/RegistrationController.php
  src/Form/AnimationType.php
  src/Form/ArticleType.php
  src/Form/CarouselType.php
  src/Form/HistoryType.php
  src/Form/RegistrationFormType.php
  templates/_admin_nav.html.twig
  templates/admin_animation/edit.html.twig
  templates/admin_article/edit.html.twig
  templates/admin_article/index.html.twig
  templates/admin_carousel/edit.html.twig
  templates/admin_history/edit.html.twig
  templates/admin_history/index.html.twig
  templates/admin_history/show.html.twig
  templates/admin_home/includes/_intro.html.twig
  templates/admin_timetable/_delete_form.html.twig
  templates/admin_timetable/index.html.twig
  templates/registration/register.html.twig
Labels: reviewed

#394 harmony for buttons..
  assets/scss/app.scss
  assets/scss/article.scss
  assets/scss/carousel.scss
  assets/scss/footer_style.scss
  assets/scss/form.scss
  assets/scss/gabare_brief_style.scss
  assets/scss/header_style.scss
  assets/scss/login_style.scss
  templates/about_us/includes/_history.html.twig
  templates/article/list.html.twig
  templates/article/show.html.twig
  templates/gabare_life/includes/_articles.html.twig
  templates/home/includes/_carousel.html.twig
  templates/home/includes/_form.html.twig
  templates/home/includes/_gabare.html.twig
Labels: reviewed

#395 fix navbar height
  assets/scss/header_style.scss
Labels: reviewed

#396 link not blue
  assets/scss/footer_style.scss
Labels: Accept this one in last, reviewed

#397 add autoload history
  src/Controller/AdminHistoryController.php
Labels: reviewed

#398 fix link
  assets/scss/admin_manual.scss
  assets/scss/app.scss
  assets/scss/timetable.scss
  templates/_admin_nav.html.twig
  templates/admin_home/includes/_intro.html.twig
Labels: reviewed

#400 notes ofr readme
  README.md
Labels: reviewed

#402 style on show article
  assets/scss/article.scss
  src/DataFixtures/ArticleFixtures.php
  templates/article/show.html.twig
Labels: reviewed

#403 fix margin on sections and hover button
  assets/images/etalage2.jpg
  assets/images/sea-min.jpg
  assets/images/welcome.jpg
  assets/scss/actualities_style.scss
  assets/scss/app.scss
  assets/scss/header_style.scss
  assets/scss/joinforms_style.scss
  assets/scss/login_style.scss
  templates/about_us/includes/_CA-Friend.html.twig
  templates/about_us/includes/_CA-Member.html.twig
  templates/about_us/includes/_employee.html.twig
  templates/article/list.html.twig
  templates/gabare_life/includes/_animation.html.twig
  templates/gabare_life/includes/_articles.html.twig
  templates/gabare_life/includes/_presse.html.twig
  templates/home/includes/_carousel.html.twig
  templates/home/includes/_welcome.html.twig
  templates/join_us/includes/_forms.html.twig
  templates/join_us/includes/_inscription.html.twig
  templates/join_us/includes/_timetable.html.twig
  templates/products/includes/_products.html.twig
  templates/security/login.html.twig
Labels: reviewed

#405 change thème and paginator
  assets/scss/article.scss
  templates/article/list.html.twig
  templates/products/includes/_products.html.twig
Labels: reviewed

#404 fix orthographe
  assets/scss/admin_manual.scss
  assets/scss/admin_menu.scss
  assets/scss/admin_style.scss
  src/Form/RegistrationFormType.php
  templates/_admin_nav.html.twig
  templates/_footer.html.twig
  templates/admin_carousel/edit.html.twig
  templates/admin_carousel/show.html.twig
  templates/admin_home/includes/_foraboutus.html.twig
  templates/admin_home/includes/_forgabarelife.html.twig
  templates/admin_home/includes/_forhomepage.html.twig
  templates/admin_home/includes/_intro.html.twig
  templates/gabare_life/includes/_presse.html.twig
  templates/gabare_life/includes/_stripe.html.twig
  templates/join_us/includes/_inscription.html.twig
  templates/registration/edit.html.twig
  templates/registration/index.html.twig
Labels: reviewed

#406 Fix card animation
  assets/scss/animation_style.scss
  templates/gabare_life/includes/_animation.html.twig
Labels: reviewed

#407 W3C join_us page
  templates/_footer.html.twig
  templates/join_us/includes/_forms.html.twig
  templates/join_us/includes/_inscription.html.twig
Labels: Priority !, reviewed

#401 fix opacity
  assets/scss/_vars.scss
  assets/scss/product_style.scss
  src/Controller/ProductController.php
  templates/products/includes/_products.html.twig
Labels: reviewed

#408 protect the route admin
  src/Controller/AdminHomeController.php
Labels: reviewed

#409 name of routes changed and fix wrap agenda
  assets/scss/timetable.scss
  src/Controller/AdminAnimationController.php
  src/Controller/AdminArticleController.php
  src/Controller/AdminCapitalController.php
  src/Controller/AdminCarouselController.php
  src/Controller/AdminHistoryController.php
  src/Controller/AdminThemeController.php
  src/Controller/AdminTimetableController.php
  src/Controller/AdminWorkerController.php
  src/Controller/ArticleController.php
  src/Controller/GabareLifeController.php
  templates/admin_history/show.html.twig
  templates/join_us/includes/_timetable.html.twig
Labels: reviewed

#411 Add placeholder theme search
  src/Form/ArticleTypeSearchType.php
Labels: reviewed

#412 test W3C on the page La vie de la Gabare
  templates/gabare_life/includes/_animation.html.twig
  templates/gabare_life/includes/_articles.html.twig
Labels: reviewed

#413 Fix worker cards
  templates/about_us/includes/_CA-Friend.html.twig
  templates/about_us/includes/_CA-Member.html.twig
  templates/about_us/includes/_employee.html.twig
Labels: reviewed

#414 dev to master
  .github/workflows/main.yml
  README.md
  assets/images/etalage2.jpg
  assets/images/sea-min.jpg
  assets/images/welcome.jpg
  assets/scss/_vars.scss
  assets/scss/actualities_style.scss
  assets/scss/admin_manual.scss
  assets/scss/admin_menu.scss
  assets/scss/admin_style.scss
  assets/scss/animation_style.scss
  assets/scss/app.scss
  assets/scss/article.scss
  assets/scss/header_style.scss
  assets/scss/joinforms_style.scss
  assets/scss/login_style.scss
  assets/scss/product_style.scss
  assets/scss/timetable.scss
  src/Controller/AdminAnimationController.php
  src/Controller/AdminArticleController.php
  src/Controller/AdminCapitalController.php
  src/Controller/AdminCarouselController.php
  src/Controller/AdminHistoryController.php
  src/Controller/AdminHomeController.php
  src/Controller/AdminThemeController.php
  src/Controller/AdminTimetableController.php
  src/Controller/AdminWorkerController.php
  src/Controller/ArticleController.php
  src/Controller/GabareLifeController.php
  src/Controller/ProductController.php
  src/DataFixtures/ArticleFixtures.php
  src/Form/ArticleTypeSearchType.php
  src/Form/RegistrationFormType.php
  templates/_admin_nav.html.twig
  templates/_footer.html.twig
  templates/about_us/includes/_CA-Friend.html.twig
  templates/about_us/includes/_CA-Member.html.twig
  templates/about_us/includes/_employee.html.twig
  templates/admin_carousel/edit.html.twig
  templates/admin_carousel/show.html.twig
  templates/admin_history/show.html.twig
  templates/admin_home/includes/_foraboutus.html.twig
  templates/admin_home/includes/_forgabarelife.html.twig
  templates/admin_home/includes/_forhomepage.html.twig
  templates/admin_home/includes/_intro.html.twig
  templates/article/list.html.twig
  templates/article/show.html.twig
  templates/gabare_life/includes/_animation.html.twig
  templates/gabare_life/includes/_articles.html.twig
  templates/gabare_life/includes/_presse.html.twig
  templates/gabare_life/includes/_stripe.html.twig
  templates/home/includes/_carousel.html.twig
  templates/home/includes/_welcome.html.twig
  templates/join_us/includes/_forms.html.twig
  templates/join_us/includes/_inscription.html.twig
  templates/join_us/includes/_timetable.html.twig
  templates/products/includes/_products.html.twig
  templates/registration/edit.html.twig
  templates/registration/index.html.twig
  templates/security/login.html.twig
Labels: reviewed

#416 namedisplay on upload input
  assets/js/vich.js
  assets/scss/admin_style.scss
  templates/admin_animation/edit.html.twig
  templates/admin_animation/new.html.twig
  templates/admin_article/edit.html.twig
  templates/admin_article/new.html.twig
  templates/admin_carousel/edit.html.twig
  templates/admin_carousel/new.html.twig
  templates/admin_history/edit.html.twig
  templates/admin_presse/edit.html.twig
  templates/admin_presse/new.html.twig
  templates/admin_worker/edit.html.twig
  templates/admin_worker/new.html.twig
  templates/base.html.twig
  webpack.config.js
Labels: reviewed

#421 S06 fix button history and ck editor
  assets/scss/app.scss
  assets/scss/history.scss
  templates/about_us/includes/_history.html.twig
  templates/article/list.html.twig
  templates/gabare_life/includes/_articles.html.twig
Labels: reviewed

#439 Change max KO pictures
  src/Entity/Animation.php
  src/Entity/Article.php
  src/Entity/Carousel.php
  src/Entity/History.php
  src/Entity/Worker.php
Labels: reviewed

#419 fix card worker
  assets/scss/pioneer_style.scss
  assets/scss/profile_card.scss
  templates/about_us/includes/_CA-Friend.html.twig
  templates/about_us/includes/_CA-Member.html.twig
  templates/about_us/includes/_employee.html.twig
  templates/about_us/includes/_pioneer.html.twig
Labels: reviewed

#443 fix carousel responsive / admin
  assets/scss/carousel.scss
  src/Entity/Carousel.php
  templates/home/includes/_carousel.html.twig
Labels: reviewed

#445 fix join us page
  templates/join_us/includes/_forms.html.twig
  templates/join_us/includes/_inscription.html.twig
  templates/join_us/includes/_timetable.html.twig
Labels: reviewed

#446 hoover green on arrows, errors w3c corrected
  assets/scss/header_style.scss
  templates/_header.html.twig
Labels: reviewed

#447 press fix
  assets/scss/presse_style.scss
  templates/gabare_life/includes/_presse.html.twig
Labels: reviewed

#448 Delete button delete - Theme
  templates/admin_home/includes/_forgabarelife.html.twig
  templates/admin_theme/_delete_form.html.twig
  templates/admin_theme/edit.html.twig
  templates/admin_theme/index.html.twig
Labels: reviewed

#453 fix w3c about us
  templates/about_us/includes/_capital.html.twig
  templates/about_us/includes/_history.html.twig
  templates/about_us/includes/_partners.html.twig
Labels: reviewed

#450 FIX flash message email
  assets/scss/actualities_style.scss
  assets/scss/app.scss
  templates/_flash_message.html.twig
  templates/gabare_life/includes/_articles.html.twig
Labels: reviewed

#454 fix products title
  assets/scss/product_style.scss
  src/Controller/ProductController.php
  templates/products/includes/_products.html.twig
Labels: reviewed

#455 FIX restoration files - articles.html.twig and actualities.scss
  assets/scss/actualities_style.scss
  templates/gabare_life/includes/_articles.html.twig
Labels: reviewed

#457 FIX focus consult button - article
  assets/scss/actualities_style.scss
Labels: reviewed

#459 Add twig function - article
  templates/gabare_life/includes/_articles.html.twig
Labels: Priority !, reviewed

#460 Add Assert image - article
  src/Entity/Article.php
Labels: reviewed

#461 change the view of the navbar
  templates/_admin_nav.html.twig
  templates/admin_home/includes/_superadmin.html.twig
Labels: reviewed
