Repository WildCodeSchool/orleans-0919-php-gabare, pull requests merged in 2020-02, with the labels that each got.

#468 Fix article
  assets/scss/app.scss
  assets/scss/article.scss
  templates/article/list.html.twig
  templates/gabare_life/includes/_articles.html.twig
Labels: reviewed

#462 fix images banners size and images parallax
  assets/images/meeting.jpg
  assets/images/nous-rejoindre-2-min.jpg
  assets/images/stripe/aboutus.webp
  assets/images/stripe/gabarelife.webp
  assets/images/stripe/home.jpg
  assets/images/stripe/joinus.webp
  assets/images/veg-basket.jpg
  assets/images/vegetables.webp
  assets/images/vegetables2.webp
  assets/scss/actualities_style.scss
  assets/scss/app.scss
  assets/scss/phone_style.scss
  assets/scss/profile_card.scss
  assets/scss/timetable.scss
  templates/about_us/includes/_stripe.html.twig
  templates/gabare_life/includes/_animation.html.twig
  templates/gabare_life/includes/_articles.html.twig
  templates/gabare_life/includes/_stripe.html.twig
  templates/home/includes/_phone.html.twig
  templates/home/includes/_welcome.html.twig
  templates/join_us/includes/_stripe.html.twig
Labels: Priority !, reviewed

#476 FIX title responsive padding
  assets/scss/animation_style.scss
  assets/scss/app.scss
  assets/scss/history.scss
  assets/scss/joinforms_style.scss
  templates/_cooperators_and_alert.html.twig
  templates/about_us/includes/_history.html.twig
  templates/join_us/includes/_inscription.html.twig
Labels: Priority !, reviewed

#458 fix superAdmin
  assets/scss/admin_style.scss
  src/Controller/RegistrationController.php
  src/Entity/User.php
  src/Form/RegistrationFormType.php
  templates/registration/edit.html.twig
Labels: reviewed

#474 line height for pionneer and responsive
  assets/scss/pioneer_style.scss
  templates/about_us/includes/_pioneer.html.twig
Labels: reviewed

#475 fix edit images admin carrousel and article
  assets/scss/carousel.scss
  src/Entity/Article.php
  src/Entity/Carousel.php
  templates/home/includes/_carousel.html.twig
Labels: reviewed

#478 fix button shadow
  assets/scss/_vars.scss
  assets/scss/app.scss
  templates/about_us/includes/_history.html.twig
  templates/gabare_life/includes/_articles.html.twig
  templates/home/includes/_gabare.html.twig
Labels: reviewed

#479 change height of video
  assets/scss/presse_style.scss
Labels: reviewed

#480 fix app et stripes
  README.md
  assets/images/door-join-us-2.jpg
  assets/images/etalage3.jpg
  assets/images/permanence.jpg
  assets/images/reunion.jpeg
  assets/images/sea-min.jpg
  assets/images/stripe/gabarelife.webp
  assets/images/veg-aisle.webp
  assets/scss/actualities_style.scss
  assets/scss/app.scss
  assets/scss/parralax.scss
  assets/scss/profile_card.scss
  assets/scss/timetable.scss
Labels: Accept this one in last, reviewed

#481 fix dev
  assets/scss/article.scss
  templates/article/list.html.twig
  templates/home/includes/_welcome.html.twig
  templates/join_us/includes/_inscription.html.twig
Labels: reviewed

#482 General FIX
  assets/scss/carousel.scss
  assets/scss/form.scss
  templates/home/includes/_carousel.html.twig
  templates/home/includes/_form.html.twig
Labels: reviewed

#483 dev to master
  README.md
  assets/images/door-join-us-2.jpg
  assets/images/etalage3.jpg
  assets/images/meeting.jpg
  assets/images/nous-rejoindre-2-min.jpg
  assets/images/permanence.jpg
  assets/images/reunion.jpeg
  assets/images/sea-min.jpg
  assets/images/stripe/aboutus.webp
  assets/images/stripe/gabarelife.webp
  assets/images/stripe/home.jpg
  assets/images/stripe/joinus.webp
  assets/images/veg-aisle.webp
  assets/images/veg-basket.jpg
  assets/images/vegetables.webp
  assets/images/vegetables2.webp
  assets/scss/_vars.scss
  assets/scss/actualities_style.scss
  assets/scss/admin_style.scss
  assets/scss/animation_style.scss
  assets/scss/app.scss
  assets/scss/article.scss
  assets/scss/carousel.scss
  assets/scss/form.scss
  assets/scss/history.scss
  assets/scss/joinforms_style.scss
  assets/scss/parralax.scss
  assets/scss/phone_style.scss
  assets/scss/pioneer_style.scss
  assets/scss/presse_style.scss
  assets/scss/profile_card.scss
  assets/scss/timetable.scss
  src/Controller/RegistrationController.php
  src/Entity/Article.php
  src/Entity/Carousel.php
  src/Entity/User.php
  src/Form/RegistrationFormType.php
  templates/_admin_nav.html.twig
  templates/_cooperators_and_alert.html.twig
  templates/about_us/includes/_history.html.twig
  templates/about_us/includes/_pioneer.html.twig
  templates/about_us/includes/_stripe.html.twig
  templates/admin_home/includes/_superadmin.html.twig
  templates/article/list.html.twig
  templates/gabare_life/includes/_animation.html.twig
  templates/gabare_life/includes/_articles.html.twig
  templates/gabare_life/includes/_stripe.html.twig
  templates/home/includes/_carousel.html.twig
  templates/home/includes/_form.html.twig
  templates/home/includes/_gabare.html.twig
  templates/home/includes/_phone.html.twig
  templates/home/includes/_welcome.html.twig
  templates/join_us/includes/_inscription.html.twig
  templates/join_us/includes/_stripe.html.twig
  templates/registration/edit.html.twig
Labels: reviewed

#484 fix master
  src/Controller/AdminArticleController.php
  src/Controller/AdminHistoryController.php
  templates/_admin_nav.html.twig
  templates/admin_article/index.html.twig
  templates/admin_home/includes/_foraboutus.html.twig
  templates/admin_home/includes/_forgabarelife.html.twig
  templates/admin_home/includes/_forhomepage.html.twig
  templates/admin_home/includes/_forjoinus.html.twig
  templates/admin_home/includes/_superadmin.html.twig
  templates/admin_home/index.html.twig
  templates/layoutAdmin.html.twig
  templates/registration/register.html.twig
Labels: reviewed

#485 dev to master
  src/Controller/AdminArticleController.php
  src/Controller/AdminHistoryController.php
  templates/_admin_nav.html.twig
  templates/admin_article/index.html.twig
  templates/admin_home/includes/_foraboutus.html.twig
  templates/admin_home/includes/_forgabarelife.html.twig
  templates/admin_home/includes/_forhomepage.html.twig
  templates/admin_home/includes/_forjoinus.html.twig
  templates/admin_home/includes/_superadmin.html.twig
  templates/admin_home/index.html.twig
  templates/layoutAdmin.html.twig
  templates/registration/register.html.twig
Labels: reviewed
